// <auto-generated />
using System;
using Catalogue.DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Catalogue.DAL.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200805233650_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Catalogue.DAL.Model.Items", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrdersId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UPC")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrdersId");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "iPhone 6s",
                            OrdersId = 1,
                            Price = 121.25m,
                            UPC = 1001m
                        },
                        new
                        {
                            Id = 2,
                            Name = "Lenovo ThinkPad",
                            OrdersId = 2,
                            Price = 215m,
                            UPC = 10010m
                        },
                        new
                        {
                            Id = 3,
                            Name = "some",
                            OrdersId = 2,
                            Price = 50m,
                            UPC = 851205m
                        },
                        new
                        {
                            Id = 4,
                            Name = "iPhone X",
                            OrdersId = 1,
                            Price = 950.50m,
                            UPC = 100101m
                        },
                        new
                        {
                            Id = 5,
                            Name = "MacBook Pro 13",
                            OrdersId = 2,
                            Price = 1200.50m,
                            UPC = 20213m
                        });
                });

            modelBuilder.Entity("Catalogue.DAL.Model.Orders", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PreviousStatus")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StatusChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2020, 8, 5, 23, 36, 49, 401, DateTimeKind.Utc).AddTicks(4083),
                            Status = 0,
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2020, 8, 5, 23, 36, 49, 401, DateTimeKind.Utc).AddTicks(5517),
                            Status = 0,
                            UserId = 3
                        });
                });

            modelBuilder.Entity("Catalogue.DAL.Model.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CustomerId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Login")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CustomerId = "customer1Mng",
                            Login = "Manager",
                            Password = "manager123"
                        },
                        new
                        {
                            Id = 2,
                            CustomerId = "customer2usr",
                            Login = "User1",
                            Password = "usr1"
                        },
                        new
                        {
                            Id = 3,
                            CustomerId = "customer3usr",
                            Login = "User2",
                            Password = "usr2"
                        });
                });

            modelBuilder.Entity("Catalogue.DAL.Model.Items", b =>
                {
                    b.HasOne("Catalogue.DAL.Model.Orders", null)
                        .WithMany("Items")
                        .HasForeignKey("OrdersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Catalogue.DAL.Model.Orders", b =>
                {
                    b.HasOne("Catalogue.DAL.Model.Users", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
